name: Automated API tests using Postman CLI

on: 
  # Evento para ejecutar el workflow manualmente desde la interfaz de GitHub
  workflow_dispatch: {}

  # También se ejecuta automáticamente cuando hay un push a la rama main
  push: 
    branches:
      - main

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests and generate HTML report
        run: |
          postman collection run "33801345-5d9e4cce-b45e-4bf9-ad98-d0ee4cc254fb" \
          -e "33801345-b6d6599f-f9a8-418c-91b1-fe6e63a48a95" \
          --reporters cli,html \
          --reporter-html-export ./newman/report.html

      - name: Configure Git for deployment
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Deploy HTML report to GitHub Pages
        if: success()
        run: |
          git clone https://github.com/${{ github.repository }}.git
          cd $(basename $_ .git)
          git checkout -B gh-pages
          cp -r ../newman/* .
          git add .
          git commit -m "Update Postman test report"
          git push https://${{ secrets.GITHUBTOKEN }}@github.com/${{ github.repository }}.git gh-pages
